# ================================================================
# yolov8_system.xdc — Timing Constraints for Block Design Bitstream
# Target: Xilinx Zynq-7020 (xc7z020clg400-1, speed grade -1)
# Top: yolov8_system_wrapper (Block Design HDL Wrapper)
#
# NOTE: Clock is generated by PS7 FCLK_CLK0 (100 MHz).
#       DO NOT use create_clock here — the PS7 IP defines it.
#       DO NOT use set_input_delay/set_output_delay — all signals
#       are internal to the SoC (PS <-> PL via AXI, no external I/O).
#
# NOTE: Synthesis/implementation optimization directives (retiming,
#       placement, routing) use get_runs which is NOT supported in XDC.
#       Apply those via TCL before launching runs instead.
# ================================================================

# No timing constraints needed — PS7 provides clock definition.
# No I/O constraints needed — all signals are internal SoC.
